"""empty message

Revision ID: 0b1e21aed25f
Revises: e5f13d7d6afa
Create Date: 2019-02-04 17:25:43.438807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1e21aed25f'
down_revision = 'e5f13d7d6afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthdate', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('firstname', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('gender', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('phonenumber', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('secondname', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'weight')
    op.drop_column('user', 'secondname')
    op.drop_column('user', 'phonenumber')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'birthdate')
    # ### end Alembic commands ###
