"""empty message

Revision ID: 2e50e616bcbd
Revises: 3434e4209655
Create Date: 2019-02-19 18:41:42.019018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e50e616bcbd'
down_revision = '3434e4209655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('is_striped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'is_striped')
    # ### end Alembic commands ###
