"""empty message

Revision ID: 7d6ce327dced
Revises: 91dfb707d34a
Create Date: 2019-02-17 16:06:29.113433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6ce327dced'
down_revision = '91dfb707d34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('student', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'student')
    # ### end Alembic commands ###
