"""empty message

Revision ID: 812785d7b0ce
Revises: 9f7ee6c72dd3
Create Date: 2019-05-13 14:38:55.134565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812785d7b0ce'
down_revision = '9f7ee6c72dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('chrono', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('tourna', sa.Integer(), nullable=True))
    op.drop_column('score', 'tournament_pos')
    op.drop_column('score', 'chrono_s')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('chrono_s', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('score', sa.Column('tournament_pos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('score', 'tourna')
    op.drop_column('score', 'chrono')
    # ### end Alembic commands ###
