"""empty message

Revision ID: 88819e6df404
Revises: 02f91fed9b17
Create Date: 2019-02-01 23:13:16.041516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88819e6df404'
down_revision = '02f91fed9b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('racket_sport_type', sa.Enum('PINGPONG', 'BADMINGTON', name='racketsporttype'), nullable=True))
    op.drop_column('team', 'racket_sport')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('racket_sport', postgresql.ENUM('PINGPONG', 'BADMINGTON', name='racketsporttype'), autoincrement=False, nullable=True))
    op.drop_column('team', 'racket_sport_type')
    # ### end Alembic commands ###
