"""empty message

Revision ID: 91dfb707d34a
Revises: ec60e832da4d
Create Date: 2019-02-14 17:03:59.854529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91dfb707d34a'
down_revision = 'ec60e832da4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('team_number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'team', ['team_number'])
    op.drop_constraint('user_team_number_key', 'user', type_='unique')
    op.drop_column('user', 'team_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('team_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_team_number_key', 'user', ['team_number'])
    op.drop_constraint(None, 'team', type_='unique')
    op.drop_column('team', 'team_number')
    # ### end Alembic commands ###
