"""empty message

Revision ID: b00a1c6ca49d
Revises: a324e7013a33
Create Date: 2019-05-01 10:54:24.737316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00a1c6ca49d'
down_revision = 'a324e7013a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'score', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.drop_column('score', 'team_id')
    # ### end Alembic commands ###
