"""empty message

Revision ID: daaa786774cc
Revises: 0b1e21aed25f
Create Date: 2019-02-13 18:51:53.863775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daaa786774cc'
down_revision = '0b1e21aed25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('valid_auth', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('valid_health', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'valid_health')
    op.drop_column('user', 'valid_auth')
    # ### end Alembic commands ###
