"""empty message

Revision ID: ec60e832da4d
Revises: 4c58b3c1a250
Create Date: 2019-02-14 17:00:08.414931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec60e832da4d'
down_revision = '4c58b3c1a250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('team_number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['team_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'team_number')
    # ### end Alembic commands ###
